[package]
name = "skeletor"
version = "2.0.1"
authors = ["Jason Joseph Nathan <jjanthanjr@gmail.com>"]
edition = "2021"
description = "A super optimized Rust scaffolding tool."
license = "MIT"
repository = "https://github.com/jasonnathan/skeletor"
homepage = "https://github.com/jasonnathan/skeletor"
documentation = "https://github.com/jasonnathan/skeletor/blob/main/README.md"

[dependencies]
clap = {version = "4.5.20", features = ["derive"]}
env_logger = "0.11.5"
indicatif = "0.17.8"
linked-hash-map = "0.5.6"
log = "0.4.22"
serde = {version = "1.0.210", features = ["derive"]}
serde_yaml = "0.9.34"
thiserror = "1.0.64"
yaml-rust = "0.4.5"

[dev-dependencies]
tempfile = "3.13.0"

