name: Package Releases

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Run tests
        run: cargo test --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          BIN_NAME="skeletor"
          OS="${{ matrix.os }}"
          ARCH=$(uname -m)
          if [ "${OS}" == "windows-latest" ]; then
              BIN_NAME+=".exe"
              zip ${BIN_NAME}-${OS}-${ARCH}.zip -j target/${{ matrix.target }}/release/${BIN_NAME}
          else
              tar -czf ${BIN_NAME}-${OS}-${ARCH}.tar.gz -C target/${{ matrix.target }}/release ${BIN_NAME}
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-binary-${{ matrix.os }}
          path: |
            skeletor-${{ matrix.os }}-$(uname -m).tar.gz
            skeletor-${{ matrix.os }}-$(uname -m).zip
