name: Package Releases

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Run tests
        run: cargo test --release --target ${{ matrix.target }}

      - name: Package binary
        shell: bash
        run: |
          BIN_NAME="skeletor"
          OS="${{ matrix.os }}"
          TARGET="${{ matrix.target }}"
          if [ "${OS}" == "windows-latest" ]; then
              BIN_NAME="${BIN_NAME}.exe"
              ARTIFACT_NAME="${BIN_NAME}-${OS}-${TARGET}.zip"
              # Check if zip is installed; if not, try installing via chocolatey.
              if ! command -v zip > /dev/null 2>&1; then
                  echo "zip command not found."
                  if command -v choco > /dev/null 2>&1; then
                      echo "Installing zip via chocolatey..."
                      choco install zip -y
                  else
                      echo "zip is not installed and cannot be installed automatically."
                      exit 1
                  fi
              fi
              zip "${ARTIFACT_NAME}" -j "target/${TARGET}/release/${BIN_NAME}"
          else
              ARTIFACT_NAME="${BIN_NAME}-${OS}-${TARGET}.tar.gz"
              tar -czf "${ARTIFACT_NAME}" -C "target/${TARGET}/release" "${BIN_NAME}"
          fi
          echo "Created ${ARTIFACT_NAME}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-binary-${{ matrix.os }}
          path: |
            skeletor-*.zip
            skeletor-*.tar.gz
