name: Update Homebrew Formula

on:
  workflow_run:
    workflows: ["Package Releases"]
    types:
      - completed

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Homebrew Tap Repository
        uses: actions/checkout@v4
        with:
          repository: jasonnathan/homebrew-tap
          token: ${{ secrets.GH_PAT }}

      - name: Fetch Latest Release Info
        id: release_info
        run: |
          VERSION=$(gh release view --repo jasonnathan/skeletor --json tagName -q ".tagName" | sed 's/v//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Download macOS Binary & Compute Checksum
        run: |
          echo "🔽 Downloading macOS binary..."
          wget -q "https://github.com/jasonnathan/skeletor/releases/download/v${VERSION}/skeletor-macos-x86_64-apple-darwin.tar.gz"

          echo "🔢 Calculating SHA256 checksum..."
          CHECKSUM=$(sha256sum skeletor-macos-x86_64-apple-darwin.tar.gz | awk '{print $1}')
          echo "SHA256=${CHECKSUM}" >> $GITHUB_ENV
          echo "✅ SHA256: ${CHECKSUM}"

      - name: Update Homebrew Formula
        run: |
          sed -i.bak "s|url \".*\"|url \"https://github.com/jasonnathan/skeletor/releases/download/v${VERSION}/skeletor-macos-x86_64-apple-darwin.tar.gz\"|" skeletor.rb
          sed -i.bak "s|sha256 \".*\"|sha256 \"${SHA256}\"|" skeletor.rb
          rm skeletor.rb.bak

      - name: Commit & Push Updated Formula
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add skeletor.rb
          git commit -m "Update Skeletor to v${VERSION}"
          git push origin main
